# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Git Checkout
    - uses: sudosubin/git-clone-action@v1.0.1
      name: Git Clone Action
      with:
        repository: comroid-git/csapi
        path: ..
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build clmath.test/clmath.test.csproj --no-restore
    - name: Test
      run: dotnet test clmath.test/clmath.test.csproj --no-build --verbosity normal
